// Generated by CoffeeScript 1.7.1
(function() {
  var NUM_BARS, bars, changeNumBars, elem, init, initElement, pingServer, rootDomain, updatePing;

  rootDomain = window.location.origin;

  bars = [];

  NUM_BARS = 4;

  elem = document.getElementById("pingr");

  changeNumBars = function(numBars) {};

  initElement = function() {
    var i, tempDiv, _i, _results;
    elem.style.display;
    _results = [];
    for (i = _i = 1; _i <= NUM_BARS; i = _i += 1) {
      tempDiv = document.createElement("div");
      tempDiv.style['background-color'] = 'green';
      tempDiv.style.width = '20px';
      tempDiv.style.height = (i * 20) + "px";
      tempDiv.style.display = "inline-block";
      tempDiv.style.margin = "5px";
      _results.push(bars[i - 1] = elem.insertBefore(tempDiv, null));
    }
    return _results;
  };

  updatePing = function(pingTime) {
    if (pingTime === -1) {

    } else {
      switch (pingTime) {
        case pingTime > 0 && pingTime <= 150:
          return changeNumBars(4);
        case pingTime > 150 && pingTime <= 300:
          return changeNumBars(3);
        case pingTime > 300 && pingTime <= 500:
          return changeNumBars(2);
        default:
          return changeNumBars(1);
      }
    }
  };

  pingServer = function(callback) {
    var http, started;
    started = Date.now();
    http = XMLHttpRequest();
    http.open("GET", rootDomain);
    return http.onreadystatechange = function() {
      var ended, pingTime;
      if (http.readyState === 4) {
        if (http.status !== 0) {
          ended = Date.now();
          pingTime = ended - started;
        } else {

        }
        return callback();
      }
    };
  };

  init = function() {
    return initElement();
  };

  setTimeout(init, 0);

}).call(this);
